version: '3.2'

services:
  web:
    build: .
    depends_on:
      - db
    env_file:
      - provision/.env
    volumes:
      - .:/wages
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
  db:
    image: postgres:12.2
    restart: always
    env_file:
      - provision/.env
    ports:
      - "5432:5432"
    volumes:
      - ./provision/db:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
  celery-worker:
    build: .
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - provision/.env
    command: celery -A wages worker -l info --concurrency=1
    volumes:
      - .:/wages
      - /var/run/docker.sock:/var/run/docker.sock
  celery-scheduler:
    build: .
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - provision/.env
    command: celery -A wages beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/wages
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-db:
