version: '3.2'

services:
  web:
    build: .
    depends_on:
      - db
    env_file:
      - provision/.env
    volumes:
      - .:/wages
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
  db:
    image: postgres:12.2
    restart: always
    env_file:
      - provision/db/.env
    ports:
      - "5433:5432"
    volumes:
      - ./provision/db:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
  ts-models-build:
    build: .
    depends_on:
      - web
      - db
    command: >
      sh -c "
        cd TensorFlow/ &&
        wget https://github.com/tensorflow/models/archive/r1.13.0.zip &&
        unzip r1.13.0.zip &&
        mv models-r1.13.0 models &&
        rm r1.13.0.zip
      "
    volumes:
      - .:/wages
volumes:
  postgres-db:
