# Generated by Django 3.0.6 on 2020-07-09 23:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import vegetable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VegetableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vegetable.models.pytorch_path)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetable.Vegetable')),
            ],
        ),
    ]
