# Generated by Django 3.0.6 on 2020-06-07 22:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='PyTorch/images')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetable.Vegetable')),
            ],
        ),
    ]
