# Generated by Django 3.0.6 on 2020-07-09 21:40

from django.db import migrations, models
import vegetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0002_vegetableimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetableimage',
            name='image',
            field=models.ImageField(upload_to=vegetable.models.pytorch_path),
        ),
    ]
